services:
  backend:
    build:
      context: ./backend
    image: lucseiler/microflow-backend:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    command: npm start

  webapp:
    build:
      context: ./webapp
    image: lucseiler/microflow-webapp:latest
    ports:
      - "8080:80"
