name: TEST Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & test application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  get-version:
    name: Get version from version.json
    runs-on: ubuntu-latest
    steps:
    - name: Get version
      run: echo "VERSION=$(jq -r .version version.json)" >> $GITHUB_ENV
