name: TEST Pipeline

on:
  push:
  pull_request:

jobs:
  version-retrieval:
    name: Version retrieval
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display current version
        run: |
          VERSION="0.0.1"
          echo "Current version: $VERSION"

          jq --arg v "$VERSION" '.version = $v' version.json > tmp.json && mv tmp.json version.json

          # Sauvegarder la version pour l'utiliser dans les étapes suivantes
          echo "VERSION=$VERSION" >> $GITHUB_ENV
