name: TEST Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    name: Build & update version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display current version
        run: |
          VERSION="0.0.1"
          echo "Current version: $VERSION"
